{
 "title": "Ranch",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "listener", "label": "Ranch listener", "query": "label_values(listener)" }
  ]
 },
 "panels": [
  { "title": "Listener: [[listener]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "listener" },
  {
   "title": "Overview",
   "type": "stat",
   "description": "The overview panel shows the current number of acceptors, compared to the configuration; the current number of connection supervisors, compared to the configuration; and the configured number of listening sockets.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ranch_num_acceptors{listener=\"$listener\"}",
     "legendFormat": "# acceptors"
    },
    {
     "expr": "ranch_num_acceptors_config{listener=\"$listener\"}",
     "legendFormat": "# configured acceptors"
    },
    {
     "expr": "ranch_num_conns_sups{listener=\"$listener\"}",
     "legendFormat": "# conns_sups"
    },
    {
     "expr": "ranch_num_conns_sups_config{listener=\"$listener\"}",
     "legendFormat": "# configured conns_sups"
    },
    {
     "expr": "ranch_num_listen_sockets_config{listener=\"$listener\"}",
     "legendFormat": "# configured listen sockets"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "The current number of connections and number of active connections at a given time. Connections are active by default and can be \"removed\" using `ranch:remove_connection/1`.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (listener)(ranch_num_connections{listener=\"$listener\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum by (listener)(ranch_num_active_connections{listener=\"$listener\"})",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "description": "The status of the acceptor processes. `exiting=1`, `suspended=2`, `runnable=3`, `garbage_collecting=4`, `running=5` and `waiting=6`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ranch_proc_status{type=\"acceptor\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "description": "The status of the connection supervisors. `exiting=1`, `suspended=2`, `runnable=3`, `garbage_collecting=4`, `running=5` and `waiting=6`.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "ranch_proc_status{type=\"conns_sup\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Reductions",
   "type": "graph",
   "description": "The number of reductions of acceptor processes at a given time. The number roughly corresponds to function calls.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_reductions{listener=\"$listener\", type=\"acceptor\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Reductions",
   "type": "graph",
   "description": "The number of reductions of connection supervisors at a given time. The number roughly corresponds to function calls.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_reductions{listener=\"$listener\", type=\"conns_sup\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Message queue length",
   "type": "graph",
   "description": "The number of messages in the queue of acceptor processes at any given time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_message_queue_len{listener=\"$listener\", type=\"acceptor\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Message queue length",
   "type": "graph",
   "description": "The number of messages in the queue of connection supervisors at any given time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_message_queue_len{listener=\"$listener\", type=\"conns_sup\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "In bytes. It is possible to obtain a per-process view of the memory usage of Ranch processes using the `ranch_proc_total_heap_size_bytes`, `ranch_proc_stack_size_bytes`, `ranch_proc_min_heap_size_bytes`, `ranch_proc_min_bin_vheap_size_bytes` and `ranch_proc_heap_size_bytes` values, filtering on the `listener`, `type` and `id`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ranch_proc_memory_bytes{listener=\"$listener\", type=\"acceptor\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "In bytes. It is possible to obtain a per-process view of the memory usage of Ranch processes using the `ranch_proc_total_heap_size_bytes`, `ranch_proc_stack_size_bytes`, `ranch_proc_min_heap_size_bytes`, `ranch_proc_min_bin_vheap_size_bytes` and `ranch_proc_heap_size_bytes` values, filtering on the `listener`, `type` and `id`.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ranch_proc_memory_bytes{listener=\"$listener\", type=\"conns_sup\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  { "title": "Listener: [[listener]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Overview",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ranch_num_acceptors{listener=\"$listener\"}",
     "legendFormat": "# acceptors"
    },
    {
     "expr": "ranch_num_acceptors_config{listener=\"$listener\"}",
     "legendFormat": "# configured acceptors"
    },
    {
     "expr": "ranch_num_conns_sups{listener=\"$listener\"}",
     "legendFormat": "# conns_sups"
    },
    {
     "expr": "ranch_num_conns_sups_config{listener=\"$listener\"}",
     "legendFormat": "# configured conns_sups"
    },
    {
     "expr": "ranch_num_listen_sockets_config{listener=\"$listener\"}",
     "legendFormat": "# listen sockets"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (listener)(ranch_num_connections{listener=\"$listener\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum by (listener)(ranch_num_active_connections{listener=\"$listener\"})",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "ranch_proc_status{type=\"acceptor\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "ranch_proc_status{type=\"conns_sup\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Reductions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_reductions{listener=\"$listener\", type=\"acceptor\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Reductions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_reductions{listener=\"$listener\", type=\"conns_sup\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Message queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_message_queue_len{listener=\"$listener\", type=\"acceptor\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Message queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ranch_proc_message_queue_len{listener=\"$listener\", type=\"conns_sup\"}[5m])",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "In bytes. It is possible to obtain a per-process view of the memory usage of Ranch processes using the `ranch_proc_total_heap_size_bytes`, `ranch_proc_stack_size_bytes`, `ranch_proc_min_heap_size_bytes`, `ranch_proc_min_bin_vheap_size_bytes` and `ranch_proc_heap_size_bytes` values, filtering on the `listener`, `type` and `id`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ranch_proc_memory_bytes{listener=\"$listener\", type=\"acceptor\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "In bytes. It is possible to obtain a per-process view of the memory usage of Ranch processes using the `ranch_proc_total_heap_size_bytes`, `ranch_proc_stack_size_bytes`, `ranch_proc_min_heap_size_bytes`, `ranch_proc_min_bin_vheap_size_bytes` and `ranch_proc_heap_size_bytes` values, filtering on the `listener`, `type` and `id`.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ranch_proc_memory_bytes{listener=\"$listener\", type=\"conns_sup\"}",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  }
 ]
}